Id: blacksouls
Name: Black Souls + RTP
Version: 1.0.0
Publisher: Shiraori
Installers:
  - Arch: x64
    InstallerType: custom
    Files:
      - Name: BLACK.SOULS.rar
        Url: https://gofile.io/d/DY5vrT
    PostInstallScript: install-blacksouls.ps1
